### ISSUE TITLE
[Dev] Argo CD application cleanup workflow templates을 통해 app group을 삭제 할 수 있다.

### ISSUE THREAD

**Issue by bluejayA** [openinfradev/decapod-issues#10]
### Describe the Story
_- [ ] A clear and concise description of what this story is._

1. Argo CD로 배포한 application을 프로젝트 (app group) 단위로 일괄 삭제할수 있는 cleanup workflow template을 작성한다.
2. TKS-Info 업데이트

### Acceptance criteria (Validation Scenario) 
_- [ ] This is something that can be verified to show that this story is satisfied._
_- [ ] This should have information for QA to validate this story._

**산출물**
- workflow template 소스
- tacoplay 또는 설치스크립트에 반영
- 매뉴얼

**Comment by robertchoi80** [comment]
appgroup 삭제 WF 자체는 완성함.
https://github.com/robertchoi80/decapod-flow/commit/55ec35bd3481b12183c184e14a73124ac83e6f37

Tks-info 에 어떻게 update할지는 월요일 tks-client 디자인 논의 후에 구현 필요.

**Comment by robertchoi80** [comment]
workflow 완성하여 PR 제출합니다
https://github.com/openinfradev/tks-flow/pull/21
https://github.com/openinfradev/decapod-flow/pull/61

**Comment by robertchoi80** [comment]
위의 이슈 원인 파악함.  app들을 한번에 일괄 삭제하다보니 CR이 완전히 삭제되기 전에 operator pod 가 삭제되면서 발생하는 이슈인 듯 하여, 아래와 같이 두 단계로 나누어 operator pod들은 나중에 삭제하도록 하니 이슈 해결된 것으로 보임.  (2회 테스트해서 이상 없는 것 확인하였으나 혹시 나중에 재발한다면 재검토 필요할 수 있음)
https://github.com/openinfradev/decapod-flow/commit/b3948404c93a3144cef1f3482c291b891fb42445

task 완료!
