### ISSUE TITLE
[Dev] Keycloak을 TKS에 설치할 수 있다

### ISSUE THREAD

**Issue by bluejayA** [openinfradev/decapod-issues#11]
### Describe the Story
_- [ ] A clear and concise description of what this story is._

TKS 서비스에서 사용자 인증을 위한 도구로 사용할 Keycloak 설치 아키텍처 및 방안 확정
- default configuration 정하기 
- helm chart & workflow template (정식형상에 맞춘) 
- 한규호님과 논의하면서 진행

### Acceptance criteria (Validation Scenario) 
_- [ ] This is something that can be verified to show that this story is satisfied._
_- [ ] This should have information for QA to validate this story._

**산출물**
- 설치 방법: Helm Chart와 Value
- 설정 가이드 및 초기설정에 대한 설명 등..
- 향후 도입 필요 사항

**완료조건**
- 정상 설치 및 사용 가능

**Comment by zugwan** [comment]
keycloak-operator 도입 고려: realm, 사용자 등 추가, 삭제 관리를 CR을 통해 할 수 있다. 연관된 다른 태스크에서 수월하게(?) 사용 가능.

**Comment by bluejayA** [comment]
이게 완료되면, 현재 https://github.com/openinfradev/tks-mgmt-cluster-deploy/blob/main/05_z1_install_keycloak.sh 이 부분은 어떻게 바뀌게 될까요?

**Comment by zugwan** [comment]
> 이게 완료되면, 현재 https://github.com/openinfradev/tks-mgmt-cluster-deploy/blob/main/05_z1_install_keycloak.sh 이 부분은 어떻게 바뀌게 될까요?

(테스트가 안되어서 아직 PR 등록 전인 ) admin-tools 워크플로우 템플릿을 실행하는 것으로 대체될 것입니다.

**Comment by seungkyua** [comment]
keycloak 설치할 때 admin 계정의 "Access Token Lifespan" 은 기본 1분(?)으로 짧게되어 있는데 4 hours 로 변경해 주세요. 로그인이나 curl 호출 시에 token 을 매번 받아와야 해서 설치시에 늘려주면 좋겠습니다.
