### ISSUE TITLE
[Dev] TKS-Management 내 Contract Git 저장소에 user cluster 용 site 내용 생성

### ISSUE THREAD

**Issue by bluejayA** [openinfradev/decapod-issues#20]
### Describe the Story
_- [ ] A clear and concise description of what this story is._

LCM 에 저장된 User 클러스터 정보 및 아이디를 기반으로 아래의 cluster-id 디렉토리 생성 및 site 내용 생성, manifests 저장소에 렌더링 되어 최종 yaml 생성까지 진행되어야함

- https://github.com/tks-management/ {contract-id}/{cluster-id}/{taco-app-group-id}
- https://github.com/tks-management/ {contract-id}-manifests/{cluster-id}/{taco-app-group-id} 

### Acceptance criteria (Validation Scenario) 
_- [ ] This is something that can be verified to show that this story is satisfied._
_- [ ] This should have information for QA to validate this story._

**Comment by Jaesang** [comment]
@intelliguy 과 겹치는 부분 확인/조율 필요
