### ISSUE TITLE
[Dev] TKS User 클러스터 ingress 컨트롤러용 ELB 생성

### ISSUE THREAD

**Issue by bluejayA** [openinfradev/decapod-issues#21]
### Describe the Story
_- [ ] A clear and concise description of what this story is._

Terraform (terraform operator + terraform cloud) 으로 생성 테스트 수행 후 완성도, 사용성 평가
==> terraform 사용법에 대한 문서화까지 
위 결과를 바탕으로 사용 불가 시 crossplane 도입

필요정보:
- VPC ID
- public subnet ids
- ec2 ids
- ingress controller가 사용할 node port for listener 등록

### Acceptance criteria (Validation Scenario) 
_- [ ] This is something that can be verified to show that this story is satisfied._
_- [ ] This should have information for QA to validate this story._

**Comment by bluejayA** [comment]
@ktkfree @kyuho24 님, 이 task는 규호님이 대부분 진행가능한걸까요? 태규님이 어느정도 commitment 해야 하는지 알려주시면 감사하겠습니다.

**Comment by kyuho24** [comment]
사용성 테스트 정도는 혼자 해도 될 듯 합니다.

**Comment by kyuho24** [comment]
Terraform cloud는 cloud에서 workspace(CLI version에서 terraform init를 하는 directory)를 관리해 주는 것 이다.
주요 부가기능으로 CSP credential등을 관리하는 Vault를 제공함.
따라서 Workspace에 접근하는 방법은 크게 아래 3가지 임
1) Terraform Cloud에 접속해서, 사람이 접근
2) Terraform Workspace를 VCS(즉,Git repo)에 연결 해서 Git repo를 통해 접근
3) Terraform Workspace에 API로 접근

**위 방식 중, 자동화를 위해 1) 3) 방안 검토 필요**

**Comment by kyuho24** [comment]
Git Ops 방식
1) Terraform workspace 생성 (workspace type을 VCS 연동으로 설정)
2) 생성된 workspace에 VCS 연결. Private Repo의 경우 보안설정
3) GitOps Trigger 방식 설정
4) Trigger 시작버튼 누르기

1)4)를 자동으로 하는 방법 추가 고민 필요.
Workspace 단위에 대한 고민 필요. Workspace별 CSP credential 관리됨으로 향후 진화를 위해서는
**Cluster당 1개의 Workspace로 관리 해야 함, 이는 Terraform 을 쓰는 이상 기본 Concept임**

**Comment by kyuho24** [comment]
Terraform Cloud를 사용는 방법:  https://tde.sktelecom.com/wiki/x/7hdcFw
Terraform operator를 사용하는 방법: https://tde.sktelecom.com/wiki/x/YQ1cFw

Terraform operator는 현 시점 기준, 전체 Framework은 동작하나, 우리가 원하는 Resource를 만들기는 어려워 보임 (사유, sample code 및 가이드 부재)
Terraform cloud기준 동작는 GitOps 형태로 확인 함.
추가 : ELB 생성을 User cluster에 설치된 elb controller가 자동으로 해 주게 하고, Terraform으로 DNS record만 생성 하는 것을 고려 할 필요 있음 (LB의 Backend pool관리를 떠 넘기기 위해서). 다만 생성된 ELB DNS는 user cluster에서는 알 수 있지만 Admin-cluster에서는 모름. 이를 해결하는 방법 찾아야 함.
