### ISSUE TITLE
[Bug] 5월 Beta TKS Cloud Service 검색 기능 대문자(영문) 검색 오류

### ISSUE THREAD

**Issue by kyuho24** [openinfradev/decapod-issues#46]
**Describe the bug**

UI Component중 검색창에 대문자를 입력하면, 검색이 않됨

**To Reproduce**
이름, 혹은 설명에 대문자가 들어가 있는 Item 생성 (e.g 설명에 QA Test)

검색에서 "qa" or "test"로 검색 시, 해당 Item 검색됨
검색에서 "QA" or "Test"로 검색 시, 검색 않됨

**Screenshots or logs (optional)**

**Server Information (please complete the following information):**

**Additional context**

**Comment by Siyeop** [comment]
모든 화면에서 동일한 문제 재현되고 있음

이 티켓으로 모든 화면 처리하고, 티켓은 1개만 등록함
