### ISSUE TITLE
[Bug] 설정 - 사용자 생성 과 사용자 수정 시 사용자 이름 길이 제한이 서로 상이함

### ISSUE THREAD

**Issue by kyuho24** [openinfradev/decapod-issues#48]
**Describe the bug**
사용자 생성 시 이름이 30자인데, 수정시 20자로 나타난다 , 하지만 막상 수정할때 30자 들어감
![Screen Shot 2023-05-25 at 3.32.22 PM.png](https://images.zenhubusercontent.com/611dac3be624ddd34503be86/beac6f80-56ab-4d2f-ae6e-f60e2404e1d3)

하지만 수정시는 30/20? 으로 나옴
![Screen Shot 2023-05-25 at 3.32.56 PM.png](https://images.zenhubusercontent.com/611dac3be624ddd34503be86/89268d56-1eac-4010-91b2-027c7a4415d8)

**To Reproduce**

**Screenshots or logs (optional)**

**Server Information (please complete the following information):**

**Additional context**

**Comment by Siyeop** [comment]
수정 시에도 30자 입력 가능하도록 길이제한 수정함
![image.png](https://images.zenhubusercontent.com/6389758ef8ac22ac6e43d1f0/1501d375-5668-42d6-858c-f0d54b710388)
