### ISSUE TITLE
[Bug] 이름/조직 명이 길어질때 표기 방안

### ISSUE THREAD

**Issue by kyuho24** [openinfradev/decapod-issues#49]
**Describe the bug**
이름과 조직이 길어 지면, 표기할때 좀 보기 좋지 않습니다. ...으로 변경해야 할까요?

![Screen Shot 2023-05-25 at 3.33.09 PM.png](https://images.zenhubusercontent.com/611dac3be624ddd34503be86/1a52d004-9cfa-45f0-80b7-f0926477fbcd)

그리고, 칸을 줄이면 동그라미가 찌그러 집니다. (이건 문제가 아닐 수도 있어 보입니다.)

![Screen Shot 2023-05-25 at 3.33.23 PM.png](https://images.zenhubusercontent.com/611dac3be624ddd34503be86/d60a4e11-0542-4578-a568-36d370a328b6)

**To Reproduce**

**Screenshots or logs (optional)**

**Server Information (please complete the following information):**

**Additional context**

**Comment by Siyeop** [comment]
@kyuho24 

> A clear and concise description of what the bug is.
이름과 조직이 길어 지면, 표기할때 좀 보기 좋지 않습니다. ...으로 변경해야 할까요?

- 사람 이름은 ... 표시하면 불쾌할수도 있을 것 같습니다.
- 조직 이름은 ... 표시해도 괜찮을 것 같긴한데요. 최대 길이를 30자로 좀 줄이고, 30자 기준으로도 부족하면 ... 처리하는거 어때 보이시나요?

> 그리고, 칸을 줄이면 동그라미가 찌그러 집니다. (이건 문제가 아닐 수도 있어 보입니다.)

- 하하 이것도 문제 맞습니다. 수정하겠습니다.
