### ISSUE TITLE
[Dev] 어플리케이션별 인증 삭제

### ISSUE THREAD

**Issue by bluejayA** [openinfradev/decapod-issues#6]
### Describe the Story
_- [ ] A clear and concise description of what this story is._

keycloak 인증후 바로 접근가능하도록 (SSO를 위해 deploy시 http, no login)
* grafana 인증삭제
* kibana 인증삭제

### Acceptance criteria (Validation Scenario) 
_- [ ] This is something that can be verified to show that this story is satisfied._
_- [ ] This should have information for QA to validate this story_

**Comment by robertchoi80** [comment]
추가 reference:
https://freestrokes.tistory.com/153
https://community.grafana.com/t/missing-grafana-oauth-cookie/21899/3 (signout-redirect-url 사용 케이스)
